version: '2.1'

services:
    # front:
    #     build:
    #         context: ./Docker/front
    #         args:
    #             - API_HOST=${FRONT_API_HOST}
    #             - PORT=8080
    #     entrypoint: "npm start"
    #     tty: true
    #     volumes:
    #         - ./data/:/front/data/
    #     expose:
    #         - "8080"
    #     ports:
    #         - "8080:8080"
    #     depends_on:
    #         mysql:
    #             condition: service_healthy

    api:
        build:
            context: ./
        entrypoint: "npm run initiate-all"
        tty: true
        volumes:
            - ./data/:/api/data/
        expose:
            - "3000"
        ports:
            - "3000:3000"
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        build:
            context: ./Docker/mysql
            args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        expose:
            - "3306"
        ports:
            - "3307:3306"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

